### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by NonsensicalOne** [indexxing/Great-Divide-Phantoms#1]
the title

**Comment by indexxing** [comment]
how is it not working lol

**Comment by NonsensicalOne** [comment]
![Screenshot_20240614-080813](https://github.com/indexxing/Great-Divide-Phantoms/assets/126889064/a51d9801-abf3-4006-a2ea-1fd972db165e)
see

**Comment by indexxing** [comment]
> ![Screenshot_20240614-080813](https://private-user-images.githubusercontent.com/126889064/339642136-a51d9801-abf3-4006-a2ea-1fd972db165e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjg4MTcsIm5iZiI6MTcxODQyODUxNywicGF0aCI6Ii8xMjY4ODkwNjQvMzM5NjQyMTM2LWE1MWQ5ODAxLWFiZjMtNDAwNi1hMmVhLTFmZDk3MmRiMTY1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwNTE1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTIwZGY0Y2Y3MzIzMDY0MjYxMTMyYTFlN2QyN2RkYWZhN2JiMmQ1NGE0MjQyOGY3NTQ2MTc0NDM1MWQwNmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GebIOPiQZCkAd4WTu6J0zLwRTmqTxMaY5XgsMUIpDXs) see

it's phantoms, not phantom
